### ISSUE TITLE
[Bug] When running in a non-Docker environment, a message is displayed regarding the storage path when saving the keystore file

### ISSUE THREAD

**Issue by alexmao-zealot** [exsat-network/client_testnet#17]
When running the client directly (not in Docker), after selecting the save path, the system prompts:

"Please ensure that the save path you set ( /root/test2/sync3/client_testnet/synchronizer ) matches the Docker mapping path. Otherwise, your keystore file may be lost. (Enter 'yes' to continue, or 'no' to go back to the previous step):"

This prompt should not appear in a non-Docker environment.

**Comment by frankoslive** [comment]
Has been updated
