### ISSUE TITLE
Optimizations and bug fixes

### ISSUE THREAD

**Issue by chenminmin4** [exsat-network/client_testnet#4]
1.Retry count configurable via .env
2.Add function isDocker to determine if the program is running inside a Docker container
3.Fix the bug where the keystore file cannot be loaded after being generated
4.Move isValidUrl and isValidJson to utils
5.Capture error information and perform error handling.
6.Fixing the pagination bug in the getTableRows method.

**Comment by frankoslive** [comment]
No. 1,2,3,4,6 has been updated
