### ISSUE TITLE
Optimizing Prompts

### ISSUE THREAD

**Issue by alexmao-zealot** [exsat-network/client_testnet#7]
Some prompts in the Client do not accurately express the functionality and need to be optimized.

**Comment by alexmao-zealot** [comment]
"Recharge BTC" needs tobe optimized to "Bridge BTC as gas fee"

**Comment by RobinHolmes** [comment]
Transaction submitted, please wait for confirmation in about 30-60 `mins` and check your email.
=>>
Transaction submitted, please wait for confirmation in about 30-60 `minutes` and check your email.

**Comment by frankoslive** [comment]
Has been updated
